### ISSUE TITLE
bad decrypt

### ISSUE THREAD

**Issue by ITProggeruz** [jesec/samfirm.js#10]
# LOG: https://pastebin.com/jC1FZH3E
 # OS: Windows

**Comment by SimonKotlar** [comment]
Hi @jesec , 

sorry to bother you, but I am facing the same issue as @ITProggeruz. 

Could you please find a moment to adress this?

Thanks a lot!

![image](https://github.com/jesec/samfirm.js/assets/36935998/c79e7ceb-0c34-480a-8919-8e5a4b97d521)

**Comment by Martyn911** [comment]
Are you affiliated with the site [SamFirm](https://samfirm.shop/) ?

**Comment by ITProggeruz** [comment]
Its with the firmware decryption issue i think

**Comment by ITProggeruz** [comment]
Or linux may*be could help

**Comment by jejo86** [comment]
Same problem here in Linux Mint 21.3

```bash
$ samfirm -m SM-A505FN -r DBT

  Model: SM-A505FN
  Region: DBT

  Latest version:
    PDA: A505FNXXU9CWB4
    CSC: A505FNOXM9CWB4
    MODEM: A505FXXU9CWB1
node:internal/crypto/cipher:193
  const ret = this[kHandle].final();
                            ^

Error: error:1C800064:Provider routines::bad decrypt
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at module.exports.__webpack_modules__.3396.exports.decryptNonce (/usr/local/lib/node_modules/samfirm/dist/index.js:11696:23)
    at module.exports.__webpack_modules__.3396.exports.handleAuthRotation (/usr/local/lib/node_modules/samfirm/dist/index.js:11714:36)
    at handleHeaders (/usr/local/lib/node_modules/samfirm/dist/index.js:11552:68)
    at /usr/local/lib/node_modules/samfirm/dist/index.js:11572:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/usr/local/lib/node_modules/samfirm/dist/index.js:11563:5) {
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v20.13.1
```

**Comment by Kai-Johnstone** [comment]
Same problem here on Arch running 6.1.1-zen kernal

```
  Model: SM-A156E
  Region: XSA

  Latest version:
    PDA: A156EDXU3BXG7
    CSC: A156EOLM3BXG7
    MODEM: A156EDXU3BXH1
node:internal/crypto/cipher:193
  const ret = this[kHandle].final();
                            ^

Error: error:1C800064:Provider routines::bad decrypt
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at module.exports.__webpack_modules__.3396.exports.decryptNonce (/home/sisyphus/.npm/_npx/56a8967cf72b9c8f/node_modules/samfirm/dist/index.js:11696:23)
    at module.exports.__webpack_modules__.3396.exports.handleAuthRotation (/home/sisyphus/.npm/_npx/56a8967cf72b9c8f/node_modules/samfirm/dist/index.js:11714:36)
    at handleHeaders (/home/sisyphus/.npm/_npx/56a8967cf72b9c8f/node_modules/samfirm/dist/index.js:11552:68)
    at /home/sisyphus/.npm/_npx/56a8967cf72b9c8f/node_modules/samfirm/dist/index.js:11572:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/sisyphus/.npm/_npx/56a8967cf72b9c8f/node_modules/samfirm/dist/index.js:11563:5) {
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v20.17.0
```

**Comment by David2k13** [comment]
me too

**Comment by Braincrasher** [comment]
Aye same, is this still being maintained?

**Comment by VivIsBee** [comment]
Same on arch w/ 6.12.8-arch1-1 kernel.

**Comment by clavium-lang** [comment]
Same on Arch.
```console
$ samfirm -m SM-S9210 -r CHC

  Model: SM-S9210
  Region: CHC

  Latest version:
    PDA: S9210ZCS4AYA1
    CSC: S9210CHC4AYA1
    MODEM: S9210ZCS4AYA1
node:internal/crypto/cipher:184
  const ret = this[kHandle].final();
                            ^

Error: error:1C800064:Provider routines::bad decrypt
    at Decipheriv.final (node:internal/crypto/cipher:184:29)
    at module.exports.__webpack_modules__.3396.exports.decryptNonce (/home/creeperxie/.npm-packages/lib/node_modules/samfirm/dist/index.js:11696:23)
    at module.exports.__webpack_modules__.3396.exports.handleAuthRotation (/home/creeperxie/.npm-packages/lib/node_modules/samfirm/dist/index.js:11714:36)
    at handleHeaders (/home/creeperxie/.npm-packages/lib/node_modules/samfirm/dist/index.js:11552:68)
    at /home/creeperxie/.npm-packages/lib/node_modules/samfirm/dist/index.js:11572:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async main (/home/creeperxie/.npm-packages/lib/node_modules/samfirm/dist/index.js:11563:5) {
  opensslErrorStack: [ 'error:1C800064:Provider routines::bad decrypt' ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v23.9.0
$ ./linux-x64 -m SM-S9210 -r CHC

  Model: SM-S9210
  Region: CHC

  Latest version:
    PDA: S9210ZCS4AYA1
    CSC: S9210CHC4AYA1
    MODEM: S9210ZCS4AYA1
Unhandled exception. System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.GetPaddingLength(ReadOnlySpan`1 block)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at SamFirm.Utils.Crypto.DecryptStringFromBytes(Byte[] cipherText, Byte[] Key)
   at SamFirm.Utils.Auth.DecryptNonce(String nonce)
   at SamFirm.Utils.FUSClient.GetFUSResponse(WebRequest wr)
   at SamFirm.Utils.FUSClient.GenerateNonce()
   at SamFirm.Program.Main(String[] args)
fish: Job 1, './linux-x64 -m SM-S9210 -r CHC' terminated by signal SIGABRT (Abort)
```
