### ISSUE TITLE
Unexpected Token Error

### ISSUE THREAD

**Issue by ksaadDE** [jesec/samfirm.js#2]
```
/usr/local/lib/node_modules/samfirm/dist/index.js:11557
            ?.find((cookie) => cookie.startsWith("JSESSIONID"))
             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

1. Tried npm run build as in the instructions AND npm i -g samfirm 
2. Also Tried wget https://github.com/jesec/samfirm.js/archive/refs/tags/v0.2.0.zip  && unzip  v0*.zip && cd v0* && npm i && npm run build && npm start

Nothing works...  same err

Greetz

**Comment by luk1337** [comment]
You need to use node.js >= 14.

**Comment by jesec** [comment]
> You need to use node.js >= 14.

^

**Comment by ksaadDE** [comment]
> > You need to use node.js >= 14.
> 
> ^

Sorry for my late reply. Thank you! I didn't recognize that Parrot downgrades node :O
